# /docs/_config.yml
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: ChattyBot
description: A desktop chatbot to manage tasks via CLI/GUI
show_downloads: false
github:
  is_project_page: true
